spring.application.name=userapp
spring.data.mongodb.uri=mongodb+srv://NguyenHau:06012005@ms10cr7ngh.wi9xme9.mongodb.net/crudusers


#minio.url=http://192.168.1.60:9000
#minio.access-key=minioadmin
#minio.secret-key=minioadmin
#minio.bucket=thigiuaki
#server.port=8080
